#Requires -Version 5.1
<#
.SYNOPSIS
    Action Packer Installation Script for Windows

.DESCRIPTION
    Installs dependencies and sets up Action Packer to run at startup using Task Scheduler.

.PARAMETER Port
    The port for the server (default: 3001)

.PARAMETER Environment
    The NODE_ENV value (default: production)

.EXAMPLE
    .\install.ps1
    .\install.ps1 -Port 3002 -Environment development
#>

param(
    [int]$Port = 3001,
    [string]$Environment = "production"
)

$ErrorActionPreference = "Stop"

# Colors and formatting
function Write-StatusMessage { param($Message) Write-Host "✓ " -ForegroundColor Green -NoNewline; Write-Host $Message }
function Write-WarningMessage { param($Message) Write-Host "⚠ " -ForegroundColor Yellow -NoNewline; Write-Host $Message }
function Write-ErrorMessage { param($Message) Write-Host "✗ " -ForegroundColor Red -NoNewline; Write-Host $Message }
function Write-InfoMessage { param($Message) Write-Host "ℹ " -ForegroundColor Cyan -NoNewline; Write-Host $Message }

# Script paths
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectDir = Split-Path -Parent $ScriptDir
$TaskName = "ActionPacker"
$LogDir = Join-Path $env:LOCALAPPDATA "ActionPacker\Logs"

Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║             Action Packer Installation Script              ║" -ForegroundColor Cyan
Write-Host "╚═══════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

Write-Host "Installation directory: $ProjectDir"
Write-Host "Port: $Port"
Write-Host "Environment: $Environment"
Write-Host ""

# Check requirements
Write-Host "Checking requirements..." -ForegroundColor Cyan

# Check Node.js
$NodePath = Get-Command node -ErrorAction SilentlyContinue
if (-not $NodePath) {
    Write-ErrorMessage "Node.js is not installed. Please install Node.js 20+ first."
    Write-Host "  Visit: https://nodejs.org/"
    exit 1
}

$NodeVersion = (node -v) -replace 'v', '' -split '\.' | Select-Object -First 1
if ([int]$NodeVersion -lt 20) {
    Write-ErrorMessage "Node.js 20+ is required. Current version: $(node -v)"
    exit 1
}
Write-StatusMessage "Node.js $(node -v) found"

# Check npm
$NpmPath = Get-Command npm -ErrorAction SilentlyContinue
if (-not $NpmPath) {
    Write-ErrorMessage "npm is not installed."
    exit 1
}
Write-StatusMessage "npm $(npm -v) found"

# Check Docker
$DockerPath = Get-Command docker -ErrorAction SilentlyContinue
if (-not $DockerPath) {
    Write-WarningMessage "Docker is not installed. Runner management will not work."
    Write-InfoMessage "Install Docker Desktop: https://docs.docker.com/desktop/install/windows/"
} else {
    try {
        docker info 2>&1 | Out-Null
        Write-StatusMessage "Docker is installed and running"
    } catch {
        Write-WarningMessage "Docker is installed but not running or not accessible"
    }
}

# Install dependencies
Write-Host ""
Write-Host "Installing dependencies..." -ForegroundColor Cyan
Push-Location $ProjectDir
try {
    npm install
    Write-StatusMessage "npm dependencies installed"
    
    Write-Host ""
    Write-Host "Building for production..." -ForegroundColor Cyan
    npm run build
    Write-StatusMessage "Production build complete"
} finally {
    Pop-Location
}

# Setup environment file
Write-Host ""
Write-Host "Setting up environment..." -ForegroundColor Cyan

$EnvFile = Join-Path $ProjectDir "backend\.env"
if (Test-Path $EnvFile) {
    Write-InfoMessage "Environment file already exists at $EnvFile"
    Write-InfoMessage "Skipping environment setup. Edit manually if needed."
} else {
    $EnvContent = @"
# Action Packer Configuration
# Generated by install.ps1 on $(Get-Date)

# Server Configuration
PORT=$Port
NODE_ENV=$Environment

# GitHub App Configuration (required for GitHub integration)
# GITHUB_APP_ID=your_app_id
# GITHUB_APP_PRIVATE_KEY_PATH=C:\path\to\private-key.pem
# GITHUB_APP_CLIENT_ID=your_client_id
# GITHUB_APP_CLIENT_SECRET=your_client_secret
# GITHUB_APP_WEBHOOK_SECRET=your_webhook_secret

# Session Configuration
# JWT_SECRET=generate_a_secure_random_string

# OAuth callback URL (set this to your public URL)
# OAUTH_CALLBACK_URL=https://your-domain.com/api/github/callback
"@
    Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8
    Write-StatusMessage "Environment template created at $EnvFile"
    Write-WarningMessage "Please edit $EnvFile to configure your GitHub App settings"
}

# Create log directory
if (-not (Test-Path $LogDir)) {
    New-Item -ItemType Directory -Path $LogDir -Force | Out-Null
}
Write-StatusMessage "Log directory created at $LogDir"

# Create the startup script
$StartupScript = Join-Path $ProjectDir "scripts\startup.ps1"
$StartupContent = @"
# Action Packer Startup Script
# Auto-generated - do not edit manually

`$ErrorActionPreference = "Continue"
`$LogDir = "$LogDir"
`$ProjectDir = "$ProjectDir"

# Redirect output to log files
`$StdOutLog = Join-Path `$LogDir "stdout.log"
`$StdErrLog = Join-Path `$LogDir "stderr.log"

# Rotate logs if they're too large (> 10MB)
if ((Test-Path `$StdOutLog) -and (Get-Item `$StdOutLog).Length -gt 10MB) {
    Move-Item `$StdOutLog "`$StdOutLog.old" -Force
}
if ((Test-Path `$StdErrLog) -and (Get-Item `$StdErrLog).Length -gt 10MB) {
    Move-Item `$StdErrLog "`$StdErrLog.old" -Force
}

Set-Location `$ProjectDir

# Set environment variables
`$env:NODE_ENV = "$Environment"
`$env:PORT = "$Port"

# Start the server
Start-Process -FilePath "npm" -ArgumentList "run", "start" -WorkingDirectory `$ProjectDir -RedirectStandardOutput `$StdOutLog -RedirectStandardError `$StdErrLog -NoNewWindow
"@
Set-Content -Path $StartupScript -Value $StartupContent -Encoding UTF8
Write-StatusMessage "Created startup script"

# Remove existing task if present
Write-Host ""
Write-Host "Installing Windows Task..." -ForegroundColor Cyan

$ExistingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($ExistingTask) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-InfoMessage "Removed existing scheduled task"
}

# Create scheduled task
$Action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -WindowStyle Hidden -File `"$StartupScript`"" -WorkingDirectory $ProjectDir

$Trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME

$Settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)

$Principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited

Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -Principal $Principal -Description "Action Packer - GitHub Actions Runner Manager" | Out-Null

Write-StatusMessage "Created scheduled task '$TaskName'"

# Start the task now
Start-ScheduledTask -TaskName $TaskName
Write-StatusMessage "Service started"

Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║              Installation Complete! 🎉                     ║" -ForegroundColor Green
Write-Host "╚═══════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-InfoMessage "Action Packer is now running at http://localhost:$Port"
Write-InfoMessage "The service will automatically start when you log in."
Write-Host ""
Write-InfoMessage "Logs are available at:"
Write-InfoMessage "  stdout: $LogDir\stdout.log"
Write-InfoMessage "  stderr: $LogDir\stderr.log"
Write-Host ""
Write-WarningMessage "Next steps:"
Write-Host "  1. Configure your GitHub App settings in backend\.env"
Write-Host "  2. Ensure Docker Desktop is running for runner management"
Write-Host "  3. Visit http://localhost:$Port to complete setup"
Write-Host ""
Write-InfoMessage "Useful commands:"
Write-Host "  .\scripts\service.ps1 status   - Check service status"
Write-Host "  .\scripts\service.ps1 stop     - Stop the service"
Write-Host "  .\scripts\service.ps1 start    - Start the service"
Write-Host "  .\scripts\service.ps1 logs     - View logs"
Write-Host ""
