#!/bin/bash
#
# Action Packer Installation Script
# Installs dependencies and sets up the service to run at startup
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Default values
INSTALL_DIR="${INSTALL_DIR:-$PROJECT_DIR}"
SERVICE_USER="${SERVICE_USER:-$(whoami)}"
PORT="${PORT:-3001}"
NODE_ENV="${NODE_ENV:-production}"

# Detect OS
OS="$(uname -s)"
case "$OS" in
    Darwin) OS_TYPE="macos" ;;
    Linux)  OS_TYPE="linux" ;;
    *)      echo -e "${RED}Unsupported operating system: $OS${NC}"; exit 1 ;;
esac

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║             Action Packer Installation Script              ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

print_status() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

# Check for required commands
check_requirements() {
    echo -e "\n${BLUE}Checking requirements...${NC}"
    
    # Check Node.js
    if ! command -v node &> /dev/null; then
        print_error "Node.js is not installed. Please install Node.js 20+ first."
        echo "  Visit: https://nodejs.org/"
        exit 1
    fi
    
    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt 20 ]; then
        print_error "Node.js 20+ is required. Current version: $(node -v)"
        exit 1
    fi
    print_status "Node.js $(node -v) found"
    
    # Check npm
    if ! command -v npm &> /dev/null; then
        print_error "npm is not installed."
        exit 1
    fi
    print_status "npm $(npm -v) found"
    
    # Check Docker (required for runner management)
    if ! command -v docker &> /dev/null; then
        print_warning "Docker is not installed. Runner management will not work."
        print_info "Install Docker: https://docs.docker.com/get-docker/"
    else
        if docker info &> /dev/null; then
            print_status "Docker is installed and running"
        else
            print_warning "Docker is installed but not running or not accessible"
            print_info "Make sure Docker is running and your user has access"
        fi
    fi
}

# Install npm dependencies
install_dependencies() {
    echo -e "\n${BLUE}Installing dependencies...${NC}"
    cd "$PROJECT_DIR"
    
    npm install
    print_status "npm dependencies installed"
    
    # Build the backend for production
    echo -e "\n${BLUE}Building for production...${NC}"
    npm run build
    print_status "Production build complete"
}

# Create environment file if it doesn't exist
setup_environment() {
    echo -e "\n${BLUE}Setting up environment...${NC}"
    
    ENV_FILE="$PROJECT_DIR/backend/.env"
    
    if [ -f "$ENV_FILE" ]; then
        print_info "Environment file already exists at $ENV_FILE"
        print_info "Skipping environment setup. Edit manually if needed."
    else
        cat > "$ENV_FILE" << EOF
# Action Packer Configuration
# Generated by install.sh on $(date)

# Server Configuration
PORT=${PORT}
NODE_ENV=${NODE_ENV}

# GitHub App Configuration (required for GitHub integration)
# GITHUB_APP_ID=your_app_id
# GITHUB_APP_PRIVATE_KEY_PATH=/path/to/private-key.pem
# GITHUB_APP_CLIENT_ID=your_client_id
# GITHUB_APP_CLIENT_SECRET=your_client_secret
# GITHUB_APP_WEBHOOK_SECRET=your_webhook_secret

# Session Configuration
# JWT_SECRET=generate_a_secure_random_string

# OAuth callback URL (set this to your public URL)
# OAUTH_CALLBACK_URL=https://your-domain.com/api/github/callback
EOF
        print_status "Environment template created at $ENV_FILE"
        print_warning "Please edit $ENV_FILE to configure your GitHub App settings"
    fi
}

# Install macOS launchd service
install_macos_service() {
    echo -e "\n${BLUE}Installing macOS service...${NC}"
    
    PLIST_NAME="com.action-packer.server"
    PLIST_PATH="$HOME/Library/LaunchAgents/${PLIST_NAME}.plist"
    LOG_DIR="$HOME/Library/Logs/ActionPacker"
    
    # Create log directory
    mkdir -p "$LOG_DIR"
    
    # Generate the plist file
    cat > "$PLIST_PATH" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${PLIST_NAME}</string>
    
    <key>ProgramArguments</key>
    <array>
        <string>$(which npm)</string>
        <string>run</string>
        <string>start</string>
    </array>
    
    <key>WorkingDirectory</key>
    <string>${PROJECT_DIR}</string>
    
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin:$(dirname $(which node))</string>
        <key>NODE_ENV</key>
        <string>${NODE_ENV}</string>
        <key>PORT</key>
        <string>${PORT}</string>
    </dict>
    
    <key>RunAtLoad</key>
    <true/>
    
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <true/>
        <key>Crashed</key>
        <true/>
    </dict>
    
    <key>ThrottleInterval</key>
    <integer>10</integer>
    
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/stdout.log</string>
    
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/stderr.log</string>
    
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
EOF
    
    print_status "Created launchd plist at $PLIST_PATH"
    
    # Unload if already loaded (ignore errors)
    launchctl unload "$PLIST_PATH" 2>/dev/null || true
    
    # Load the service
    launchctl load "$PLIST_PATH"
    print_status "Service loaded and will start at login"
    
    # Start the service now
    launchctl start "$PLIST_NAME"
    print_status "Service started"
    
    echo ""
    print_info "Logs are available at:"
    print_info "  stdout: $LOG_DIR/stdout.log"
    print_info "  stderr: $LOG_DIR/stderr.log"
    echo ""
    print_info "Useful commands:"
    print_info "  View status:  launchctl list | grep action-packer"
    print_info "  Stop service: launchctl stop $PLIST_NAME"
    print_info "  Start service: launchctl start $PLIST_NAME"
    print_info "  Unload (disable): launchctl unload $PLIST_PATH"
}

# Install Linux systemd service
install_linux_service() {
    echo -e "\n${BLUE}Installing Linux systemd service...${NC}"
    
    SERVICE_NAME="action-packer"
    SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
    
    # Check if we have sudo access
    if ! sudo -n true 2>/dev/null; then
        print_warning "sudo access required for systemd service installation"
        print_info "You will be prompted for your password"
    fi
    
    # Generate the systemd service file
    sudo tee "$SERVICE_FILE" > /dev/null << EOF
[Unit]
Description=Action Packer - GitHub Actions Runner Manager
Documentation=https://github.com/depoll/action-packer
After=network.target docker.service
Wants=docker.service

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${PROJECT_DIR}
ExecStart=$(which npm) run start
Restart=always
RestartSec=10

# Environment
Environment=NODE_ENV=${NODE_ENV}
Environment=PORT=${PORT}
Environment=PATH=/usr/local/bin:/usr/bin:/bin:$(dirname $(which node))

# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=false
ReadWritePaths=${PROJECT_DIR}/backend/data /var/run/docker.sock
PrivateTmp=true

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=action-packer

[Install]
WantedBy=multi-user.target
EOF
    
    print_status "Created systemd service at $SERVICE_FILE"
    
    # Reload systemd
    sudo systemctl daemon-reload
    print_status "Systemd daemon reloaded"
    
    # Enable the service
    sudo systemctl enable "$SERVICE_NAME"
    print_status "Service enabled (will start at boot)"
    
    # Start the service
    sudo systemctl start "$SERVICE_NAME"
    print_status "Service started"
    
    echo ""
    print_info "Useful commands:"
    print_info "  View status: sudo systemctl status $SERVICE_NAME"
    print_info "  View logs:   sudo journalctl -u $SERVICE_NAME -f"
    print_info "  Stop:        sudo systemctl stop $SERVICE_NAME"
    print_info "  Restart:     sudo systemctl restart $SERVICE_NAME"
    print_info "  Disable:     sudo systemctl disable $SERVICE_NAME"
}

# Main installation flow
main() {
    echo "Installation directory: $PROJECT_DIR"
    echo "Service user: $SERVICE_USER"
    echo "Operating system: $OS_TYPE"
    echo "Port: $PORT"
    echo ""
    
    check_requirements
    install_dependencies
    setup_environment
    
    # Install platform-specific service
    case "$OS_TYPE" in
        macos) install_macos_service ;;
        linux) install_linux_service ;;
    esac
    
    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║              Installation Complete! 🎉                     ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    print_info "Action Packer is now running at http://localhost:${PORT}"
    print_info "The service will automatically start when you log in."
    echo ""
    print_warning "Next steps:"
    echo "  1. Configure your GitHub App settings in backend/.env"
    echo "  2. Ensure Docker is running for runner management"
    echo "  3. Visit http://localhost:${PORT} to complete setup"
    echo ""
}

# Handle command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --port)
            PORT="$2"
            shift 2
            ;;
        --user)
            SERVICE_USER="$2"
            shift 2
            ;;
        --env)
            NODE_ENV="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --port PORT     Set the server port (default: 3001)"
            echo "  --user USER     Set the service user (default: current user)"
            echo "  --env ENV       Set NODE_ENV (default: production)"
            echo "  --help, -h      Show this help message"
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

main
